# config/schema/rating_scorer.schema.yml
rating_scorer.settings:
  type: config_object
  label: 'Rating Scorer settings'
  mapping:
    default_minimum_ratings:
      type: integer
      label: 'Default minimum ratings threshold'
    bayesian_assumed_average:
      type: float
      label: 'Bayesian assumed average'
    default_rating:
      type: float
      label: 'Default rating value'
    default_num_ratings:
      type: integer
      label: 'Default number of ratings'

    scenario_rating_deviation:
      type: float
      label: 'Scenario rating deviation (%)'
    scenario_reviews_deviation:
      type: float
      label: 'Scenario reviews deviation (%)'
