# config/schema/rating_scorer.schema.yml
rating_scorer.settings:
  type: config_object
  label: 'Rating Scorer settings'
  mapping:
    default_minimum_ratings:
      type: integer
      label: 'Default minimum ratings threshold'
    bayesian_assumed_average:
      type: float
      label: 'Bayesian assumed average'
    default_rating:
      type: float
      label: 'Default rating value'
    default_num_ratings:
      type: integer
      label: 'Default number of ratings'
    default_method:
      type: string
      label: 'Default scoring method'
    higher_rating_deviation:
      type: float
      label: 'Higher Rating scenario - rating deviation (%)'
    higher_rating_reviews_deviation:
      type: float
      label: 'Higher Rating scenario - reviews deviation (%)'
    more_reviews_rating_deviation:
      type: float
      label: 'More Reviews scenario - rating deviation (%)'
    more_reviews_reviews_deviation:
      type: float
      label: 'More Reviews scenario - reviews deviation (%)'
