# config/schema/rating_scorer.schema.yml
rating_scorer.settings:
  type: config_object
  label: 'Rating Scorer settings'
  mapping:
    default_minimum_ratings:
      type: integer
      label: 'Default minimum ratings threshold'
    default_rating:
      type: float
      label: 'Default rating value'
    default_num_ratings:
      type: integer
      label: 'Default number of ratings'
    default_method:
      type: string
      label: 'Default scoring method'
